.editorconfig
.pre-commit-config.yaml
insights/insights/doctype/data_source/data_source.py

Currently since port is Data type it's being sent as string to DB connector. 
Fix: cast to int before saving. 
```
Traceback (most recent call last):
File "apps/insights/insights/insights/doctype/data_source/data_source.py", line 360, in connect_to_db
db.connect()
File "apps/frappe/frappe/database/database.py", line 92, in connect
self._conn = self.get_connection()
File "apps/frappe/frappe/database/mariadb/database.py", line 86, in get_connection
conn = pymysql.connect(
File "env/lib/python3.10/site-packages/pymysql/connections.py", line 290, in __init__
raise ValueError("port should be of type int")
ValueError: port should be of type int
```
---
Few more observations:
- Setup/onboarding form doesn't clarify which fields are mandatory. 
- host can be made optional - localhost as default
- …

fix: cast port to integer

---

frontend/src/components/Query/Column/ColumnExpressionPicker.vue

When adding an Expression, if the field type is date or datetime. The following error occurs:
```
Traceback (most recent call last):
File "apps/frappe/frappe/app.py", line 58, in application
response = frappe.api.handle()
File "apps/frappe/frappe/api.py", line 54, in handle
return frappe.handler.handle()
File "apps/frappe/frappe/handler.py", line 45, in handle
data = execute_cmd(cmd)
File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
return frappe.call(method, **frappe.form_dict)
File "apps/frappe/frappe/__init__.py", line 1584, in call
return fn(*args, **newargs)
File "apps/frappe/frappe/handler.py", line 310, in run_doc_method
response = doc.run_method(method, **args)
File "apps/frappe/frappe/model/document.py", line 925, in run_method
out = Document.hook(fn)(self, *args, …
```

fix: set Date/Datetime fields in expression builder.

---

requirements.txt

Installing on 3.11 requires building from source which is long and slow process. 
Latest pandas versions ship wheels. Tested locally. 
Nothing breaking from what I can tell:
- https://pandas.pydata.org/pandas-docs/version/1.5.0/whatsnew/v1.5.0.html#backwards-incompatible-api-changes
- https://pandas.pydata.org/pandas-docs/version/1.5.1/whatsnew/v1.5.1.html

build: bump pandas & python 3.11 support

---

frontend/src/components/Sidebar.vue
frontend/src/pages/Avatars.vue
frontend/src/pages/ManageTeamMembers.vue
frontend/src/pages/Teams.vue

`imageURL` -> `image` in latest frappe-ui.
Avatar was not loading correctly due to this:
Now it is:
> Just noticed, my first contribution to insights 😃

fix: update prop name for Avatar component

---

insights/overrides.py

None is now assumed as False by framework

fix: perm hooks should always send true/false

---

frontend/vite.config.js

Same motivation as: https://github.com/frappe/builder/pull/118
- repo (e.g. when using a git worktree) isn't guaranteed to be called `insights` 
- the import isn't used anymore and breaks alt build root builds

fix: alt build root

---

insights/hooks.py

The passwords of my other Data Sources got corrupted on `export-fixtures`

fix: Only export standard Data Sources as fixtures

---

requirements.txt

Delete dummy requirements file - now requirements are defined and picked only from `project.dependencies` defined in pyproject.toml

chore: Delete requirements.txt

---

pyproject.toml

Since numpy's latest release (2.0.0) last night, is [ABI breaking](https://numpy.org/devdocs/dev/depending_on_numpy.html#numpy-2-abi-handling), numpy has to be <2.0.0. This has been fixed already in latest pandas 2.1.x

Upgrade pandas patch version

---

frontend/src/router.ts

Change the path of page 404 not found from path "not-found" --> "/:pathMatch(.*)*" 
then move to the end of the router array

fix catch all 404 page not found page

---

frontend/src/components/Sidebar.vue

issue #222
moved query above data source in sidebar.

refactor: sidebar UX

---

pyproject.toml

No breaking changes, according to the [release notes](https://pandas.pydata.org/docs/whatsnew/index.html).
Ensures compatibility with other apps like erpnext_germany.

chore: bump pandas to v2.2.2

---

frontend/src/query/ScriptQueryEditor.vue

```python
pandas = frappe._dict()
pandas.DataFrame = pd.DataFrame
pandas.read_csv = pd.read_csv
pandas.json_normalize = pd.json_normalize
```
Reference: https://github.com/frappe/insights/blob/develop/insights/insights/doctype/insights_query/insights_script_query.py#L118-L130

fix(script-query): Script query help should reference pandas instead

---

frontend/src/widgets/AxisChart/getAxisChartOptions.js

I didn't add any way to set this in the UI. 
I intend to set this to 'dataMin' and 'dataMax' directly InsightsChart.options field
I need prettier charts. Please!
References: 
- https://echarts.apache.org/en/option.html#yAxis.min
- https://echarts.apache.org/en/option.html#yAxis.max

feat: add support for clipping y-axis with `yAxis.min` and `yAxis.max`

---

frontend/src/components/AppShell.vue

This PR addresses the issue where the sidebar appears momentarily on public links before being hidden. This fix ensures that the sidebar does not appear where sidebar shouldn't load, providing a cleaner and more consistent user experience for public links.
**Before:**
when the link is loaded,
**Changes:**
In AppShell.vue, hidesidebar defined as a ref with true value then added a watch for route and update hidesidebar as per route.meta of new route.
**Related Issue:** #299

fix(ux): Sidebar Appearing Briefly on Public Links in Frappe Insights

---

insights/insights/doctype/insights_data_source_v3/ibis_utils.py

```python
Traceback (most recent call last):
File "apps/frappe/frappe/app.py", line 115, in application
response = frappe.api.handle(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "apps/frappe/frappe/api/__init__.py", line 49, in handle
data = endpoint(**arguments)
^^^^^^^^^^^^^^^^^^^^^
File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
return frappe.handler.handle()
^^^^^^^^^^^^^^^^^^^^^^^
File "apps/frappe/frappe/handler.py", line 49, in handle
data = execute_cmd(cmd)
^^^^^^^^^^^^^^^^
File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
return frappe.call(method, **frappe.form_dict)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "apps/frappe/frappe/__init__.py", line 1822, in call
return fn(*args, **newargs)
^^^^^^^^^^^^^^^^^^^^
File …
```

fix(v3): Add Boolean, UUID in supported column types

---

frontend/src2/charts/components/DonutChartConfigForm.vue
frontend/src2/charts/helpers.ts
frontend/src2/types/chart.types.ts

This PR adds the inline labels feature for the Donut Chart in v3, which was previously available in v2 but missing in v3. The feature allows labels to be displayed inside the chart.

Add Inline Labels Feature for Donut Chart in v3

---

frontend/src/components/Table/TanstackTable.vue

This PR enhances the table component by:
- Bolding and center-aligning the table headers.
- Right-aligning numeric columns.
-  Adding hover effects on rows for better user interactivity.
**Closes #311** — This PR addresses the feature request for bolding and centering table headings as described in the issue #311
**Before:**
**After:**

fix: right-aligned numbers in tables

---

insights/api/__init__.py

Hi,
I encountered an issue when trying to load a CSV file, exported from Google Sheets, that contained NAT or NAN values.
Example output after been read by Ibis:
```json
{
"Product Code": "zzzzzz",
"Project Code": "zzzzzz",
"Accounting Period": NaT,
"Doc N°": nan,
"Order": None,
"Contract": None,
}
```
In this case it doesn't throw any error in the UI, the dialog only shows **No data to display.**
In the console we have the following error: `Error: SyntaxError: JSON.parse: unexpected character at line 1 column 1714 of the JSON data`
My proposal is to apply a fillna on the first 50 rows before they are sent back to the UI, so that the JSON can be correctly read on the client side.
Please let me know if you disagree with this solution.
Have a nice day !

fix: Fill NAN and NAT fields before sending them to the frontend

---

frontend/src2/helpers/index.ts

**Description:**
Updated the formatNumber function to include minimumFractionDigits, ensuring numbers retain trailing zeros.
**Linked Issue**
Closes #403 
**Before:**
**After:**

fix: preserve trailing zeros in number formatting

---

insights/insights/doctype/insights_data_source_v3/insights_data_source_v3.py

And it will cause after request hooks to always fail

Fix: Before request hook might not be executed.

---

frontend/src2/components/AppSidebar.vue

**Description:**
This PR adds persistence for the sidebar state (collapsed or expanded) using localStorage via @vueuse/core. The sidebar will remember its state across sessions, enhancing the user experience.
**Changes:**
Used useStorage to sync the sidebar state with localStorage.
Defaults to expanded (false) if no value exists in localStorage.
**Testing:**
Toggle the sidebar and refresh the page to confirm the state persists.
Clear localStorage and reload to verify the default expanded state.

feat: Add persistent sidebar state using localStorage

---

frontend/src2/query/components/NativeQueryEditor.vue

This PR addresses two key improvements in the Query Editor's DataTable component:
1. **Enable Pagination**: Ensures all rows are accessible in the DataTable by enabling pagination.
2. **Resolve Sorting Issue**: Implements dynamic query updates for column sorting, allowing users to sort data by ascending, descending, or default order.
**Before:**
[before.webm](https://github.com/user-attachments/assets/f6da37c0-915d-46f5-9d95-17d31c3ce8a7)
**After:**
[after.webm](https://github.com/user-attachments/assets/affe8566-2548-4c1d-aca1-c6c359cf42fd)

fix: enable pagination and resolve sorting issue in DataTable for Query Editor

---

frontend/src/widgets/AxisChart/getAxisChartOptions.js
frontend/src/widgets/Bar/BarOptions.vue
frontend/src/widgets/Row/RowOptions.vue

This PR adds support for data labels in bar charts, allowing users to toggle labels on or off via a new show_data_labels option. Labels are positioned on top of bars for stacked charts and formatted using getShortNumber for better readability.
Closes: #274

feat(v2): Add data labels to bar charts

---

frontend/src2/charts/components/DrillDown.vue

- Fixed the issue with the total row count displaying incorrectly in the drill-down dialog footer.
- Added a "Load All Rows" button to fetch and display all rows when required.
- Ensured the button is conditionally displayed only when not all rows are loaded.
This PR addresses both pagination and total row count issues in the drill-down dialog.
Closes #405:
**Before Fix**
**After Fix**
[After.webm](https://github.com/user-attachments/assets/47fd3dc6-d6b7-42d1-b700-d0a4b85ab10a)

fix: enhance drill-down dialog with total row count and load all rows

---

frontend/src/widgets/AxisChart/getAxisChartOptions.js
frontend/src2/charts/helpers.ts

- Ensures zero values are excluded from the tooltip.
- Sorts tooltip data in descending order for better readability.
Closes #390
**Before Fix**
**After Fix**

fix: filter and sort tooltip values

---

frontend/src2/dashboard/DashboardChart.vue

This PR fixes the issue where **drill-down was not working in TableChart.vue** because `chart` was `undefined`.  
closes: #447 
- Used **`provide('chart', chart)`** in `DashboardChart.vue` so it can be accessed in `TableChart.vue`.
- Now, `chart` is **available** in `TableChart.vue`, enabling drill-down functionality.

Fix drill-down not working in Table Chart inside Dashboard

---

insights/insights/doctype/insights_data_source_v3/ibis_utils.py
insights/insights/doctype/insights_data_source_v3/insights_data_source_v3.json
insights/insights/doctype/insights_data_source_v3/insights_data_source_v3.py

Added the possibility to execute stored procedures by adding the exec word to the conditions and using raw_sql() from ibis instead of sql(). 
Also added the possibility to use Current Date as variable (@Today) in queries. It will be replaced by the current server date in the following format ('YYYY-MM-DD').
Use:
`EXEC usp_report_Sales @valuationDate = @Today, @ShowSerialNumbers=1`

feat: support stored procedure execution

---

frontend/src2/dashboard/DashboardText.vue

Auto and minimum height for the textarea with fixed height while adding text in a dashboard.

fix: adjust height for textarea in text widget.

---

frontend/src2/dashboard/DashboardFilter.vue
frontend/src2/dashboard/DashboardFilterEditor.vue
frontend/src2/dashboard/DashboardText.vue
frontend/src2/dashboard/dashboard.ts

Replace default text with placeholders in dashboard widgets.
- Fixes UX issue where default text appeared as actual content user need to clear that and enter text

fix: Replace default text with placeholders in dashboard widgets

---

insights/insights/doctype/insights_data_source/sources/frappe_db.py
insights/insights/doctype/insights_data_source_v3/connectors/frappe_db.py

Since Frappe v14, read-only queries can be addressed to a secondary database server (replica). This helps offload the primary server. I noticed that this framework feature was not used in Insights. This PR intends to fix that.
> https://docs.frappe.io/framework/v14/user/en/guides/database-settings/setup-read-from-secondary-db

feat(db): Read from database replica if available

---

frontend/src2/components/DataTable.vue

fix: show `null` values as `null` instead of `0`

---

frontend/src2/index.css
frontend/src2/query/components/NativeQueryEditor.vue
frontend/src2/query/components/ScriptQueryEditor.vue
frontend/src2/query/query.ts

feat: Add `Force Execute` option to bypass SQL result cache
- Cached SQL results were making it difficult to debug queries, especially after inserting new data. Re-running the same SQL would return stale results due to caching, rather than reflecting the latest data.
- This PR adds a Force Execute button to the SQL editor, allowing users to explicitly bypass the cache and run the query fresh.
https://github.com/user-attachments/assets/2a0217a4-22bf-48c4-a198-3b18a03db6f0

feat: add force execution option to SQL editor

---

frontend/src2/workbook/WorkbookQueryEmptyState.vue

This is a small yet a glaring typo mistake in the insights UI

Fixed typo WorkbookQueryEmptyState.vue

---

frontend/src/utils/query/results.js
frontend/src2/query/helpers.ts

Dashboard tables in Insights app were displaying raw HTML tags instead of clean text, making data unreadable and unprofessional.
**Before:**
**After:**
closes: #630

fix: strip HTML tags from dashboard table cells for clean text display

---

frontend/src2/dashboard/DashboardList.vue

Fixes #596
Resolves issue where long dashboard titles were truncated in the dashboard list view.

fix: enable multiline display for long dashboard titles in list view

---

frontend/src2/dashboard/Dashboard.vue
frontend/src2/dashboard/dashboard.ts
frontend/src2/types/workbook.types.ts
insights/insights/doctype/insights_dashboard_v3/insights_dashboard_v3.py

shows 'open workbook'  option in dashboards page only when users have read permission for it

fix: add permission check for opening workbook in dashboard
